version : '2'
services:
  mdb:
    image: mongo
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITBD_ROOT_USER: "umarabox"
      MONGO_INITBD_ROOT_PASSWORD: "secret"
     
    networks: 
      - lexclassnet
    volumes:
      - /home/umarabox/Desktop/assign
  rdb: 
    image: redis
    ports: 
      - "6379:6379"
    networks:
      - lexclassnet
  mydb: 
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
    networks:
      - lexclassnet
  api: 
    image: umarabox/lexdocker:v100
    scale: 3
    ports: 
      - "3000:3000"
    networks: 
      - lexclassnet
networks: 
  lexclassnet:
    driver: bridge  