version: "3"

services:
  mdb:
    image: mongo
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "umar"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
      MONGO_INITDB_DATABASE: "mdb"
    networks:
      - mynet
    volumes:
      - /home/umarabox/Desktop/docker-compose/src/storage

  rdb:
    image: redis
    ports:
      - "6379"
    networks:
      - mynet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
   
    networks:
      - mynet

  api:
    image: umarabox/eg:v100
    restart: always
    ports:
      - "9000"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
